# Gesture sensitivity
PINCH_THRESHOLD = 50
GESTURE_HOLD_TIME = 0.5
GESTURE_CHECK_INTERVAL = 3

# Visual feedback
FEEDBACK_DURATION = 1.5
SELECTION_COLOR = (0,255,255)
CLIPBOARD_INDICATOR_SIZE = 80

# Drawing parameters
BRUSH_THICKNESS = 15
ERASER_THICKNESS = 50

# UI positions
CLIPBOARD_INDICATOR_X = 1200
CLIPBOARD_INDICATOR_Y = 650
GESTURE_GUIDE_X = 20
GESTURE_GUIDE_Y = 40
